import { Question } from './types';

export const QUESTIONS: Question[] = [
  // MISIÓN 1: DIGITAL LIFE & GAMING
  { id: 1, mission: 1, text: "I need to enter my ________ to start the game.", options: ["password", "keyboard", "battery", "mouse", "volume"], correctAnswer: "password", hint: "Es tu palabra secreta para entrar.", translation: "Password (Contraseña)", explanation: "Usamos 'password' para proteger nuestras cuentas." },
  { id: 2, mission: 1, text: "Wait! The game is ________. I have a bad internet connection.", options: ["lagging", "running", "playing", "jumping", "flying"], correctAnswer: "lagging", hint: "Cuando el juego va lento o se traba.", translation: "Lagging (Trabado/Lento)", explanation: "Lagging se refiere al retraso en la conexión." },
  { id: 3, mission: 1, text: "I am a pro ________. I play every day.", options: ["gamer", "game", "gaming", "games", "gamers"], correctAnswer: "gamer", hint: "Persona que juega videojuegos.", translation: "Gamer (Jugador)", explanation: "Añadimos -er al final de 'game' para designar a la persona." },
  { id: 4, mission: 1, text: "My ________ is very fast. I type quickly.", options: ["keyboard", "screen", "tablet", "cable", "plug"], correctAnswer: "keyboard", hint: "Lo usas para escribir letras.", translation: "Keyboard (Teclado)", explanation: "Key (tecla) + Board (tabla) = Teclado." },
  { id: 5, mission: 1, text: "Let's play ________! I can see you on the server.", options: ["online", "offline", "inline", "outline", "backline"], correctAnswer: "online", hint: "Conectado a internet.", translation: "Online (En línea)", explanation: "Online significa estar conectado a la red." },
  { id: 6, mission: 1, text: "I have a new ________. He is my best teammate.", options: ["friend", "enemy", "boss", "monster", "animal"], correctAnswer: "friend", hint: "Persona con la que te llevas bien.", translation: "Friend (Amigo)", explanation: "Friend es alguien con quien compartes juegos y charlas." },
  { id: 7, mission: 1, text: "The game ________ is full. I can't enter.", options: ["server", "service", "seven", "saver", "silver"], correctAnswer: "server", hint: "Donde se alojan las partidas multijugador.", translation: "Server (Servidor)", explanation: "El servidor es la computadora central del juego." },
  { id: 8, mission: 1, text: "I need to ________ to my account.", options: ["login", "look", "listen", "learn", "leave"], correctAnswer: "login", hint: "Entrar con tu usuario.", translation: "Login (Iniciar sesión)", explanation: "Login es la acción de identificarse en un sistema." },
  { id: 9, mission: 1, text: "I am on ________ 10. It is very difficult!", options: ["level", "lever", "label", "layer", "liver"], correctAnswer: "level", hint: "Etapa o fase de un juego.", translation: "Level (Nivel)", explanation: "Cada fase de un juego se llama level." },
  { id: 10, mission: 1, text: "The ________ is too small. I want a bigger monitor.", options: ["screen", "scene", "scream", "screw", "score"], correctAnswer: "screen", hint: "Donde ves las imágenes.", translation: "Screen (Pantalla)", explanation: "Screen es la superficie donde aparece la imagen." },

  // MISIÓN 2: TECH GADGETS
  { id: 11, mission: 2, text: "My ________ is in my pocket.", options: ["smartphone", "smartwatch", "smartboard", "smartcard", "smartcar"], correctAnswer: "smartphone", hint: "Tu teléfono inteligente.", translation: "Smartphone (Teléfono)", explanation: "Smart (inteligente) + Phone (teléfono)." },
  { id: 12, mission: 2, text: "Help! My phone ________ is 1%.", options: ["battery", "button", "bottom", "bottle", "battle"], correctAnswer: "battery", hint: "La energía del dispositivo.", translation: "Battery (Batería)", explanation: "Battery almacena la energía eléctrica." },
  { id: 13, mission: 2, text: "Is the ________ working? I need internet.", options: ["WiFi", "Water", "Wind", "Wheel", "Wall"], correctAnswer: "WiFi", hint: "Conexión inalámbrica.", translation: "WiFi", explanation: "WiFi es el nombre de la red inalámbrica." },
  { id: 14, mission: 2, text: "I watch ________ on YouTube.", options: ["videos", "voices", "visits", "visions", "vases"], correctAnswer: "videos", hint: "Imágenes con sonido.", translation: "Videos (Videos)", explanation: "Video es el formato visual más popular hoy." },
  { id: 15, mission: 2, text: "I use my ________ to draw digital art.", options: ["tablet", "table", "ticket", "target", "tower"], correctAnswer: "tablet", hint: "Como un teléfono pero más grande.", translation: "Tablet (Tableta)", explanation: "Una tablet es ideal para dibujar y jugar." },
  { id: 16, mission: 2, text: "I have a new ________ on my phone. It is a game.", options: ["app", "all", "ant", "age", "art"], correctAnswer: "app", hint: "Abreviación de aplicación.", translation: "App (Aplicación)", explanation: "App es un programa de software para móviles." },
  { id: 17, mission: 2, text: "Turn up the ________! I love this song.", options: ["volume", "value", "valley", "voice", "voter"], correctAnswer: "volume", hint: "Qué tan fuerte suena algo.", translation: "Volume (Volumen)", explanation: "Volume es la intensidad del sonido." },
  { id: 18, mission: 2, text: "I need a ________ for my laptop.", options: ["charger", "change", "charge", "chance", "chair"], correctAnswer: "charger", hint: "El cable para dar energía.", translation: "Charger (Cargador)", explanation: "Charger viene de 'charge' (cargar)." },
  { id: 19, mission: 2, text: "The ________ is very clear. It is 4K.", options: ["camera", "camel", "canal", "candy", "cabin"], correctAnswer: "camera", hint: "Lo que captura las fotos.", translation: "Camera (Cámara)", explanation: "La camera sirve para tomar fotos o grabar." },
  { id: 20, mission: 2, text: "My ________ are wireless. No cables!", options: ["headphones", "headaches", "headbands", "headsets", "headlights"], correctAnswer: "headphones", hint: "Lo que pones en tus oídos.", translation: "Headphones (Auriculares)", explanation: "Head (cabeza) + Phones (teléfonos)." },

  // MISIÓN 3: URBAN STYLE & ACTION
  { id: 21, mission: 3, text: "I ride my ________ in the park.", options: ["skateboard", "keyboard", "cardboard", "surfboard", "board"], correctAnswer: "skateboard", hint: "Tabla con 4 ruedas.", translation: "Skateboard (Patineta)", explanation: "Skate (patinar) + Board (tabla)." },
  { id: 22, mission: 3, text: "I love my new ________. They are cool sneakers!", options: ["shoes", "show", "shop", "shot", "shut"], correctAnswer: "shoes", hint: "Lo que usas en los pies.", translation: "Shoes (Zapatos)", explanation: "Sneakers es un tipo de 'shoes' deportivos." },
  { id: 23, mission: 3, text: "It is cold. I am wearing a ________.", options: ["hoodie", "hood", "house", "horse", "honey"], correctAnswer: "hoodie", hint: "Sudadera con capucha.", translation: "Hoodie (Sudadera/Polerón)", explanation: "Hoodie viene de 'hood' (capucha)." },
  { id: 24, mission: 3, text: "I am recording a ________ for my channel.", options: ["vlog", "blog", "flag", "plug", "slug"], correctAnswer: "vlog", hint: "Video sobre tu vida.", translation: "Vlog (Video-blog)", explanation: "Vlog es un diario en formato de video." },
  { id: 25, mission: 3, text: "The ________ is full of people and cars.", options: ["city", "country", "corner", "cloud", "center"], correctAnswer: "city", hint: "Lugar grande con edificios.", translation: "City (Ciudad)", explanation: "City es una zona urbana grande." },
  { id: 26, mission: 3, text: "Can you ________? I like this beat.", options: ["dance", "dark", "door", "desk", "duck"], correctAnswer: "dance", hint: "Moverse al ritmo de la música.", translation: "Dance (Bailar)", explanation: "Dance es una forma de expresión física." },
  { id: 27, mission: 3, text: "I use my ________ to record the parkour.", options: ["GoPro", "GoFree", "GoFast", "GoPlay", "GoSlow"], correctAnswer: "GoPro", hint: "Marca de cámara de acción.", translation: "GoPro (Cámara de acción)", explanation: "Es un nombre común para cámaras de deporte." },
  { id: 28, mission: 3, text: "The ________ is the street art on the wall.", options: ["graffiti", "graphic", "giraffe", "gravity", "grammar"], correctAnswer: "graffiti", hint: "Pintura en las paredes de la ciudad.", translation: "Graffiti (Grafiti)", explanation: "Arte urbano hecho con spray." },
  { id: 29, mission: 3, text: "I wear a ________ to protect my head.", options: ["cap", "cup", "cat", "car", "can"], correctAnswer: "cap", hint: "Gorra para el sol.", translation: "Cap (Gorra)", explanation: "Cap es un accesorio muy común en el estilo urbano." },
  { id: 30, mission: 3, text: "Let's take a ________ together!", options: ["selfie", "self", "select", "sell", "send"], correctAnswer: "selfie", hint: "Foto a uno mismo.", translation: "Selfie (Autofoto)", explanation: "Selfie es un término global para estas fotos." },

  // MISIÓN 4: SPACE & SCI-FI
  { id: 31, mission: 4, text: "The ________ is flying to Mars.", options: ["rocket", "rock", "robot", "pocket", "jacket"], correctAnswer: "rocket", hint: "Vehículo espacial.", translation: "Rocket (Cohete)", explanation: "Un cohete viaja fuera de la atmósfera." },
  { id: 32, mission: 4, text: "I saw an ________ with three eyes!", options: ["alien", "alone", "alive", "alike", "align"], correctAnswer: "alien", hint: "Ser de otro planeta.", translation: "Alien (Alienígena)", explanation: "Alien significa 'extranjero' o de otro mundo." },
  { id: 33, mission: 4, text: "The ________ is full of stars.", options: ["galaxy", "gal", "game", "gate", "garage"], correctAnswer: "galaxy", hint: "Conjunto de sistemas solares.", translation: "Galaxy (Galaxia)", explanation: "Nuestra galaxia es la Vía Láctea." },
  { id: 34, mission: 4, text: "The ________ is a machine that thinks.", options: ["robot", "room", "road", "rope", "rock"], correctAnswer: "robot", hint: "Autómata inteligente.", translation: "Robot (Robot)", explanation: "Robot viene de una palabra que significa 'trabajo'." },
  { id: 35, mission: 4, text: "Jump into the ________ to go home!", options: ["portal", "port", "part", "party", "poster"], correctAnswer: "portal", hint: "Puerta mágica o tecnológica.", translation: "Portal (Portal)", explanation: "Un portal conecta dos lugares instantáneamente." },
  { id: 36, mission: 4, text: "Be careful with the ________ sword.", options: ["laser", "later", "layer", "leader", "ladder"], correctAnswer: "laser", hint: "Luz muy potente y concentrada.", translation: "Laser (Láser)", explanation: "Láser es luz amplificada." },
  { id: 37, mission: 4, text: "I want to be an ________ and go to space.", options: ["astronaut", "astronomy", "athlete", "actor", "author"], correctAnswer: "astronaut", hint: "Persona que viaja al espacio.", translation: "Astronaut (Astronauta)", explanation: "Astro (estrella) + Nauta (navegante)." },
  { id: 38, mission: 4, text: "The ________ is the center of our system.", options: ["Sun", "Star", "Space", "Saturn", "Sky"], correctAnswer: "Sun", hint: "Nuestra estrella más cercana.", translation: "Sun (Sol)", explanation: "El Sol nos da luz y calor." },
  { id: 39, mission: 4, text: "My ________ is out of fuel.", options: ["spaceship", "starship", "smallship", "skyship", "spaceshop"], correctAnswer: "spaceship", hint: "Nave espacial.", translation: "Spaceship (Nave espacial)", explanation: "Space (espacio) + Ship (barco/nave)." },
  { id: 40, mission: 4, text: "Is there ________ on other planets?", options: ["life", "leaf", "left", "lift", "light"], correctAnswer: "life", hint: "Seres vivos.", translation: "Life (Vida)", explanation: "Buscamos señales de vida en el espacio." },

  // MISIÓN 5: MODERN SCHOOL & LIFE
  { id: 41, mission: 4, text: "I put my books in my ________.", options: ["backpack", "backdoor", "backyard", "backstage", "backhand"], correctAnswer: "backpack", hint: "Mochila escolar.", translation: "Backpack (Mochila)", explanation: "Back (espalda) + Pack (paquete)." },
  { id: 42, mission: 5, text: "I have a big ________ for science class.", options: ["project", "protect", "profit", "product", "problem"], correctAnswer: "project", hint: "Trabajo especial o maqueta.", translation: "Project (Proyecto)", explanation: "Un proyecto es un trabajo largo de investigación." },
  { id: 43, mission: 5, text: "The ________ is where I keep my coat.", options: ["locker", "lock", "looker", "lucky", "lunch"], correctAnswer: "locker", hint: "Casillero con llave.", translation: "Locker (Casillero)", explanation: "Lock (cerradura) + er = Casillero." },
  { id: 44, mission: 5, text: "It is time for ________! Let's play!", options: ["break", "bread", "brick", "bridge", "bring"], correctAnswer: "break", hint: "Recreo o descanso.", translation: "Break (Descanso/Recreo)", explanation: "A 'break' es un tiempo libre entre clases." },
  { id: 45, mission: 5, text: "I use a ________ to write notes.", options: ["notebook", "noteboard", "notecase", "notecard", "mailbox"], correctAnswer: "notebook", hint: "Cuaderno para apuntes.", translation: "Notebook (Cuaderno)", explanation: "Note (nota) + Book (libro)." },
  { id: 46, mission: 5, text: "The ________ explains the lesson.", options: ["teacher", "student", "singer", "player", "worker"], correctAnswer: "teacher", hint: "Persona que enseña.", translation: "Teacher (Profesor/a)", explanation: "Teach (enseñar) + er = Profesor." },
  { id: 47, mission: 5, text: "I am a ________ in level 6.", options: ["student", "study", "studio", "stadium", "station"], correctAnswer: "student", hint: "Persona que estudia.", translation: "Student (Estudiante)", explanation: "Eres un estudiante si estás aprendiendo." },
  { id: 48, mission: 5, text: "I have too much ________ today.", options: ["homework", "homeland", "homemade", "homebase", "homerun"], correctAnswer: "homework", hint: "Tareas para casa.", translation: "Homework (Tarea)", explanation: "Home (casa) + Work (trabajo)." },
  { id: 49, mission: 5, text: "I have a great ________ for the story!", options: ["idea", "item", "iron", "into", "inch"], correctAnswer: "idea", hint: "Un pensamiento nuevo y creativo.", translation: "Idea (Idea)", explanation: "Una idea es un pensamiento brillante." },
  { id: 50, mission: 5, text: "Let's go to the ________ for lunch.", options: ["cafeteria", "cafe", "camera", "cabin", "castle"], correctAnswer: "cafeteria", hint: "Donde comes en la escuela.", translation: "Cafeteria (Cafetería/Comedor)", explanation: "Es el lugar de comida escolar." }
];