import { Question, ScrambleQuestion } from './types';

export const SCRAMBLE_QUESTIONS: ScrambleQuestion[] = [
  { id: 101, sentence: "I want to go to the beach today", translation: "Quiero ir a la playa hoy" },
  { id: 102, sentence: "My favorite ice cream is very cold", translation: "Mi helado favorito está muy frío" },
  { id: 103, sentence: "The sun is shining in the sky", translation: "El sol está brillando en el cielo" },
  { id: 104, sentence: "We are packing our suitcases for travel", translation: "Estamos haciendo las maletas para viajar" },
  { id: 105, sentence: "I love swimming in the big pool", translation: "Amo nadar en la piscina grande" },
  { id: 106, sentence: "The roller coaster is very exciting and fast", translation: "La montaña rusa es muy emocionante y rápida" },
  { id: 107, sentence: "We are sleeping in a big tent tonight", translation: "Estamos durmiendo en una carpa grande esta noche" },
  { id: 108, sentence: "Can I have some cold orange juice", translation: "¿Puedo tomar un poco de jugo de naranja frío?" },
  { id: 109, sentence: "The plane is flying over the clouds", translation: "El avión está volando sobre las nubes" },
  { id: 110, sentence: "I am taking photos of the mountains", translation: "Estoy tomando fotos de las montañas" }
];

export const QUESTIONS: Question[] = [
  // MISIÓN 1: BEACH PARTY (Sol, Arena, Mar)
  { id: 1, mission: 1, text: "I am building a big ________ on the sand.", options: ["sandcastle", "snowball", "pizza", "computer", "pencil"], correctAnswer: "sandcastle", hint: "Un castillo hecho de arena.", translation: "Sandcastle (Castillo de arena)", explanation: "Sand (arena) + Castle (castillo)." },
  { id: 2, mission: 1, text: "I need my ________ to protect my eyes from the sun.", options: ["sunglasses", "gloves", "socks", "boots", "hat"], correctAnswer: "sunglasses", hint: "Lentes para el sol.", translation: "Sunglasses (Gafas de sol)", explanation: "Sun (sol) + Glasses (lentes)." },
  { id: 3, mission: 1, text: "The ________ are very big and blue today.", options: ["waves", "caves", "paths", "clouds", "trees"], correctAnswer: "waves", hint: "Movimiento del agua en el mar.", translation: "Waves (Olas)", explanation: "Las olas son perfectas para surfear." },
  { id: 4, mission: 1, text: "I put ________ on my skin to avoid a sunburn.", options: ["sunscreen", "shampoo", "toothpaste", "ketchup", "water"], correctAnswer: "sunscreen", hint: "Crema protectora.", translation: "Sunscreen (Protector solar)", explanation: "Screen significa proteger o pantalla contra el sol." },
  { id: 5, mission: 1, text: "I love eating ________ in a cone.", options: ["ice cream", "hamburger", "spaghetti", "chicken", "apple"], correctAnswer: "ice cream", hint: "Un postre muy frío.", translation: "Ice cream (Helado)", explanation: "Ice (hielo) + Cream (crema)." },
  { id: 6, mission: 1, text: "The ocean is very ________. I can swim well.", options: ["calm", "angry", "small", "dry", "hot"], correctAnswer: "calm", hint: "Cuando el agua está tranquila.", translation: "Calm (Tranquilo)", explanation: "Calm describe un mar sin muchas olas." },
  { id: 7, mission: 1, text: "I am using my ________ to dry my body.", options: ["towel", "paper", "shirt", "blanket", "leaf"], correctAnswer: "towel", hint: "Lo usas después de nadar.", translation: "Towel (Toalla)", explanation: "Una toalla seca la humedad." },
  { id: 8, mission: 1, text: "Look! I found a beautiful ________ on the beach.", options: ["seashell", "smartphone", "key", "coin", "button"], correctAnswer: "seashell", hint: "Concha de mar.", translation: "Seashell (Concha marina)", explanation: "Sea (mar) + Shell (cáscara/concha)." },
  { id: 9, mission: 1, text: "Let's go ________! The water is great.", options: ["swimming", "running", "jumping", "sleeping", "reading"], correctAnswer: "swimming", hint: "Acción de nadar.", translation: "Swimming (Nadando)", explanation: "Swim + ing = nadando." },
  { id: 10, mission: 1, text: "The ________ is shining very bright.", options: ["sun", "moon", "star", "lamp", "fire"], correctAnswer: "sun", hint: "Nuestra fuente de luz de día.", translation: "Sun (Sol)", explanation: "El sol es el protagonista del verano." },

  // MISIÓN 2: CAMPING ADVENTURE (Bosque, Naturaleza)
  { id: 11, mission: 2, text: "We are sleeping in a ________ in the forest.", options: ["tent", "house", "hotel", "bus", "cave"], correctAnswer: "tent", hint: "Tu casa portátil de lona.", translation: "Tent (Carpa/Tienda)", explanation: "Una tent se arma para acampar." },
  { id: 12, mission: 2, text: "I am cooking marshmallows over the ________.", options: ["campfire", "fridge", "table", "bed", "window"], correctAnswer: "campfire", hint: "Fuego para calentar y cocinar.", translation: "Campfire (Fogata)", explanation: "Camp (campamento) + Fire (fuego)." },
  { id: 13, mission: 2, text: "I use a ________ to see in the dark night.", options: ["flashlight", "mirror", "book", "spoon", "comb"], correctAnswer: "flashlight", hint: "Lámpara de mano.", translation: "Flashlight (Linterna)", explanation: "Flash (destello) + Light (luz)." },
  { id: 14, mission: 2, text: "The ________ are very tall and green.", options: ["trees", "flowers", "rocks", "clouds", "grass"], correctAnswer: "trees", hint: "Plantas gigantes del bosque.", translation: "Trees (Árboles)", explanation: "Muchos trees forman un bosque (forest)." },
  { id: 15, mission: 2, text: "I carry my water and snacks in my ________.", options: ["backpack", "pocket", "hat", "hand", "box"], correctAnswer: "backpack", hint: "Mochila para caminar.", translation: "Backpack (Mochila)", explanation: "Back (espalda) + Pack (paquete)." },
  { id: 16, mission: 2, text: "Listen to the ________ singing in the morning.", options: ["birds", "cats", "lions", "dogs", "cows"], correctAnswer: "birds", hint: "Animales que vuelan.", translation: "Birds (Pájaros)", explanation: "Los birds cantan al amanecer." },
  { id: 17, mission: 2, text: "Let's go for a ________ on the mountain path.", options: ["hike", "sleep", "bath", "game", "movie"], correctAnswer: "hike", hint: "Caminata por la naturaleza.", translation: "Hike (Caminata/Senderismo)", explanation: "Hiking es caminar por senderos." },
  { id: 18, mission: 2, text: "The lake water is very ________.", options: ["fresh", "salty", "sour", "bitter", "dry"], correctAnswer: "fresh", hint: "Agua limpia y dulce.", translation: "Fresh (Fresca)", explanation: "Fresh describe agua no salada y limpia." },
  { id: 19, mission: 2, text: "I am looking at the ________ with my telescope.", options: ["stars", "cars", "planes", "boats", "houses"], correctAnswer: "stars", hint: "Puntos brillantes de la noche.", translation: "Stars (Estrellas)", explanation: "En el campo se ven mejor las stars." },
  { id: 20, mission: 2, text: "Be careful with the ________! They can bite.", options: ["mosquitoes", "elephants", "giraffes", "whales", "birds"], correctAnswer: "mosquitoes", hint: "Insectos pequeños que pican.", translation: "Mosquitoes (Mosquitos)", explanation: "Usamos repelente para los mosquitoes." },

  // MISIÓN 3: AIRPORT & TRAVEL (Viajes, Aviones)
  { id: 21, mission: 3, text: "I need my ________ to travel to another country.", options: ["passport", "diary", "marker", "toy", "brush"], correctAnswer: "passport", hint: "Documento oficial de viaje.", translation: "Passport (Pasaporte)", explanation: "Sin passport no puedes salir del país." },
  { id: 22, mission: 3, text: "My ________ is very heavy. It has all my clothes.", options: ["suitcase", "purse", "wallet", "envelope", "hat"], correctAnswer: "suitcase", hint: "Maleta de viaje.", translation: "Suitcase (Maleta)", explanation: "Suit (traje) + Case (estuche/caja)." },
  { id: 23, mission: 3, text: "The ________ is ready to take off.", options: ["airplane", "bicycle", "skateboard", "scooter", "truck"], correctAnswer: "airplane", hint: "Vehículo que vuela.", translation: "Airplane (Avión)", explanation: "Air (aire) + Plane (plano/avión)." },
  { id: 24, mission: 3, text: "The ________ welcomes us on the plane.", options: ["pilot", "chef", "doctor", "fireman", "farmer"], correctAnswer: "pilot", hint: "Persona que maneja el avión.", translation: "Pilot (Piloto)", explanation: "El pilot vuela la aeronave." },
  { id: 25, mission: 3, text: "We are waiting at the ________ for our flight.", options: ["gate", "door", "window", "roof", "floor"], correctAnswer: "gate", hint: "Puerta de embarque.", translation: "Gate (Puerta/Puerta de embarque)", explanation: "La gate es donde entras al avión." },
  { id: 26, mission: 3, text: "I have my ________. My seat is 12A.", options: ["ticket", "money", "photo", "map", "key"], correctAnswer: "ticket", hint: "Boleto de viaje.", translation: "Ticket (Boleto/Pasaje)", explanation: "El ticket indica tu número de asiento." },
  { id: 27, mission: 3, text: "Look out the ________ to see the clouds.", options: ["window", "wall", "ceiling", "mirror", "screen"], correctAnswer: "window", hint: "Ventanilla del avión.", translation: "Window (Ventana)", explanation: "Window seat es el asiento de ventana." },
  { id: 28, mission: 3, text: "Fasten your ________ please.", options: ["seatbelt", "shoes", "glasses", "hat", "watch"], correctAnswer: "seatbelt", hint: "Cinturón de seguridad.", translation: "Seatbelt (Cinturón de seguridad)", explanation: "Seat (asiento) + Belt (cinturón)." },
  { id: 29, mission: 3, text: "Our ________ is New York City.", options: ["destination", "start", "back", "home", "inside"], correctAnswer: "destination", hint: "Lugar a donde vas.", translation: "Destination (Destino)", explanation: "Es el punto final del viaje." },
  { id: 30, mission: 3, text: "The flight ________ is four hours.", options: ["time", "day", "year", "month", "week"], correctAnswer: "time", hint: "Duración del vuelo.", translation: "Time (Tiempo/Duración)", explanation: "El tiempo que dura el viaje." },

  // MISIÓN 4: THEME PARK FUN (Atracciones)
  { id: 31, mission: 4, text: "The ________ is so fast! I want to scream.", options: ["roller coaster", "carousel", "swing", "slide", "bench"], correctAnswer: "roller coaster", hint: "Montaña rusa.", translation: "Roller coaster (Montaña rusa)", explanation: "La atracción más emocionante del parque." },
  { id: 32, mission: 4, text: "I am eating pink ________.", options: ["cotton candy", "pizza", "sushi", "salad", "soup"], correctAnswer: "cotton candy", hint: "Nube de azúcar dulce.", translation: "Cotton candy (Algodón de azúcar)", explanation: "Cotton (algodón) + Candy (caramelo)." },
  { id: 33, mission: 4, text: "Let's wait in the ________ for the ride.", options: ["line", "circle", "square", "box", "hole"], correctAnswer: "line", hint: "Fila de personas.", translation: "Line/Queue (Fila/Cola)", explanation: "In line significa estar en la fila." },
  { id: 34, mission: 4, text: "The ________ of the park is a big mouse.", options: ["mascot", "boss", "worker", "animal", "statue"], correctAnswer: "mascot", hint: "Personaje del parque.", translation: "Mascot (Mascota/Personaje)", explanation: "La mascot representa al parque." },
  { id: 35, mission: 4, text: "I love the ________ wheel. It is very high.", options: ["Ferris", "bike", "car", "small", "water"], correctAnswer: "Ferris", hint: "La rueda de la fortuna.", translation: "Ferris wheel (Noria/Rueda de la fortuna)", explanation: "Lleva el nombre de su creador, Mr. Ferris." },
  { id: 36, mission: 4, text: "The park is full of ________ and fun.", options: ["magic", "boring", "sad", "dark", "angry"], correctAnswer: "magic", hint: "Algo especial y fantástico.", translation: "Magic (Magia)", explanation: "Magic describe el ambiente de felicidad." },
  { id: 37, mission: 4, text: "I won a giant ________ at the game booth.", options: ["teddy bear", "pencil", "apple", "shoe", "sandwich"], correctAnswer: "teddy bear", hint: "Oso de peluche.", translation: "Teddy bear (Oso de peluche)", explanation: "Un premio muy común." },
  { id: 38, mission: 4, text: "The ________ is a slow ride with horses.", options: ["carousel", "plane", "rocket", "train", "boat"], correctAnswer: "carousel", hint: "Carrusel o calesita.", translation: "Carousel (Carrusel)", explanation: "Gira con música y caballos." },
  { id: 39, mission: 4, text: "Let's go to the water ________! I'm hot.", options: ["park", "shop", "school", "library", "bank"], correctAnswer: "park", hint: "Parque con toboganes de agua.", translation: "Water park (Parque acuático)", explanation: "Un parque para mojarse y jugar." },
  { id: 40, mission: 4, text: "I bought a cool ________ to remember the trip.", options: ["souvenir", "milk", "bread", "egg", "meat"], correctAnswer: "souvenir", hint: "Recuerdo de un lugar.", translation: "Souvenir (Recuerdo)", explanation: "Algo que compras para no olvidar el viaje." },

  // MISIÓN 5: CITY EXPLORER (Turismo en la ciudad)
  { id: 41, mission: 5, text: "I am using a ________ to find the museum.", options: ["map", "mirror", "brush", "key", "coin"], correctAnswer: "map", hint: "Dibujo que muestra las calles.", translation: "Map (Mapa)", explanation: "El map te ayuda a no perderte." },
  { id: 42, mission: 5, text: "The ________ tells us the history of the city.", options: ["guide", "dog", "baby", "cat", "bird"], correctAnswer: "guide", hint: "Persona que explica el tour.", translation: "Guide (Guía)", explanation: "El tour guide sabe mucho de la ciudad." },
  { id: 43, mission: 5, text: "Let's take a ________ in front of the monument.", options: ["photo", "bath", "nap", "shower", "jump"], correctAnswer: "photo", hint: "Imagen capturada con cámara.", translation: "Photo (Foto)", explanation: "Say cheese! para la photo." },
  { id: 44, mission: 5, text: "We are visiting a ________ with old skeletons.", options: ["museum", "park", "store", "gym", "cinema"], correctAnswer: "museum", hint: "Lugar de arte o historia.", translation: "Museum (Museo)", explanation: "En el museum vemos cosas antiguas." },
  { id: 45, mission: 5, text: "The ________ bus has two floors.", options: ["tourist", "school", "police", "fire", "fast"], correctAnswer: "tourist", hint: "Bus para ver la ciudad.", translation: "Tourist bus (Bus turístico)", explanation: "Ideal para ver los monumentos." },
  { id: 46, mission: 5, text: "I want to eat a ________ pizza for lunch.", options: ["delicious", "ugly", "sad", "angry", "broken"], correctAnswer: "delicious", hint: "Cuando algo sabe muy bien.", translation: "Delicious (Delicioso)", explanation: "Yummy! es similar a delicious." },
  { id: 47, mission: 5, text: "This building is very ________ and tall.", options: ["famous", "tiny", "hidden", "lost", "quiet"], correctAnswer: "famous", hint: "Que todo el mundo conoce.", translation: "Famous (Famoso)", explanation: "Un lugar muy conocido." },
  { id: 48, mission: 5, text: "Let's walk around the ________.", options: ["square", "triangle", "line", "dot", "corner"], correctAnswer: "square", hint: "La plaza central.", translation: "Square (Plaza/Cuadrado)", explanation: "The main square es la plaza principal." },
  { id: 49, mission: 5, text: "I am writing a ________ to my grandma.", options: ["postcard", "poster", "pizza", "pillow", "phone"], correctAnswer: "postcard", hint: "Tarjeta que se envía por correo.", translation: "Postcard (Tarjeta postal)", explanation: "Post (correo) + Card (tarjeta)." },
  { id: 50, mission: 5, text: "The city ________ are very friendly.", options: ["people", "monsters", "aliens", "ghosts", "robots"], correctAnswer: "people", hint: "Las personas que viven ahí.", translation: "People (Gente/Personas)", explanation: "Las personas hacen la ciudad alegre." }
];
